### ISSUE TITLE
Launching SnoozeTabs from the firefox menu results in the right part of it clipped.

### ISSUE THREAD

**Issue by imyxh** [bwinton/SnoozeTabs#221] opened 2017-02-27 03:58 UTC
On Ubuntu 16.04 and Firefox Developer Edition 52.0a2
Screenshot (gif):
![peek 2017-02-26 19-57](https://cloud.githubusercontent.com/assets/12703838/23348336/e0c45220-fc5d-11e6-85e9-be739906bac7.gif)

**Comment by lmorchard** [comment] 2017-02-27 16:32
@imyxh Could you by chance open up the Browser Console under developer tools and see if there are any messages like "SnoozeTabs (FE) resize ###"? ### should be the width that the panel ended up being, and that will be helpful for me to try fixing this.

Going to try reproducing this myself too. I think this is just one more variant width for that panel that we need to account for in styles

**Comment by imyxh** [comment] 2017-02-28 01:12
@lmorchard These are the only error messages I get in the console from opening snoozetabs, and they happen even when I open it from the toolbar:
```
DEPRECATION WARNING: _getTabForBrowser` is now deprecated, please use `getTabForBrowser
You may find more details about this deprecation at: https://developer.mozilla.org/docs/Mozilla/Tech/XUL/Method/getTabForBrowser
chrome://browser/content/tabbrowser.xml 422 _getTabForBrowser
chrome://ublock/content/js/vapi-background.js 388 getTabForBrowser
chrome://ublock/content/js/vapi-background.js 509 vAPI.tabs.getTabId
chrome://ublock/content/js/vapi-background.js 1366 vAPI.net.registerListeners/locationChangedListener
  Deprecated.jsm:79

NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]  frameModule.js:39

NS_BINDING_ABORTED: Component returned failure code: 0x804b0002 (NS_BINDING_ABORTED) [nsIStreamListener.onStartRequest]
```

**Comment by bwinton** [comment] 2017-03-02 16:25
Another dupe of #179, maybe?

**Comment by lmorchard** [comment] 2017-03-07 17:47
Going to say this is #179

**Closed by lmorchard** 2017-03-07 17:47 UTC
