### ISSUE TITLE
Multiple Snoozes opening at same time causes first open to fail

### ISSUE THREAD

**Issue by AussieGit** [bwinton/SnoozeTabs#369] opened 2017-11-08 00:04 UTC
If multiple snoozed tabs are opened at same time, the first tab will fail to open. As you can see from screenshot, I'm using Tree Style Tab (has current compatibility bug with FF Quantum that the default FF tabs are still visible) of which 4 snoozed tabs were opened at same time and first tab (highlighted in TST & FF tabs) has short description but clicking on tab only shows the info of you in the address bar.

Using FF 57 0b13 (64bit) on Windows 7

![snoozetab issue](https://user-images.githubusercontent.com/26198909/32524093-21fe2996-c459-11e7-806d-0ae83dc4e902.PNG)

**Comment by SoftVision-CarmenFat** [comment] 2017-11-08 13:36
Hi @AussieGit, thanks for reporting this.

Tested with latest Snooze Tabs v.1.0.21, using Nightly 58.0a1 (2017-11-08) on Windows 10 x64 and was unable to reproduce it.
I tried with both "Next Open" and "Pick a Date/Time" options (in this case I set the tabs to snooze at the same time) and all the tabs were correctly brought back.

Can you please try to reproduce this issue with a clean new profile?

**Comment by lmorchard** [comment] 2018-01-18 19:53
I wasn't able to reproduce this, either. Going to close this for now, but we can reopen if it happens again

**Closed by lmorchard** 2018-01-18 19:53 UTC
