### ISSUE TITLE
Unable to install Snooze Tabs

### ISSUE THREAD

**Issue by Icy-of-Melbourne** [bwinton/SnoozeTabs#224] opened 2017-02-28 02:34 UTC
Hey there,

Not sure if this is the right spot to say this, however the test pilot channel in the IRC was empty so here I be.
Basically when I click the 'install' button to download the addon, the button changes to 'enabling' however nothing seems to be happening, no matter how long I wait.

https://pageshot.net/c901SevRG0Eii4r4/testpilot.firefox.com

Any suggestions?

Firefox 51.0.1, Windows 10 x64

**Comment by bwinton** [comment] 2017-02-28 02:49
You should report this on the [Test Pilot issue page](https://github.com/mozilla/testpilot/issues/)…  (But this repo was a good guess.  🙂  I also suspect it's a duplicate of another issue they've seen, but don't know which one.)

**Closed by bwinton** 2017-02-28 02:49 UTC
