### ISSUE TITLE
Tabs snoozed until 'later today' didn't unsnooze

### ISSUE THREAD

**Issue by potch** [bwinton/SnoozeTabs#234] opened 2017-03-02 23:33 UTC
<img width="368" alt="screenshot 2017-03-02 14 56 10" src="https://cloud.githubusercontent.com/assets/253470/23531901/a3dfd76e-ff5d-11e6-84f6-5958f59fa0dd.png">

**Comment by bwinton** [comment] 2017-03-03 00:09
Huh.  @lmorchard?  I've heard a couple of reports of this happening.  Maybe we should have a dev-mode that shows extra info (like next scheduled alarm) somewhere…

**Comment by lmorchard** [comment] 2017-03-03 22:23
Right now, dev-mode is the dev build of the extension, which logs the next timer every time the wake timer is updated. The production build doesn't log anything - which maybe we should change.

**Comment by colinfrei** [comment] 2017-03-07 06:43
I've seen this as well, for tabs that are snoozed until tomorrow - the tab actually reopened about 22.5 hours too late.

Is there any way to run the dev build without building it myself? I'm happy to debug/send logs.

**Comment by ckprice** [comment] 2017-03-07 18:51
@pdehaan can you try to reproduce?

**Comment by lmorchard** [comment] 2017-03-09 18:11
Yeah, having trouble reproducing this myself. Set a few tabs to wake "later today" a few times over the past few days and they all worked. Also looks like the timer's getting set correctly, at least for me right now:

<img width="814" alt="screenshot 2017-03-09 13 08 49" src="https://cloud.githubusercontent.com/assets/21687/23763918/96d2632c-04c9-11e7-9136-8bb1ef46bbf1.png">

<img width="318" alt="screenshot 2017-03-09 13 09 31" src="https://cloud.githubusercontent.com/assets/21687/23763938/a90b39e2-04c9-11e7-8820-53afb3d0dad0.png">

[Logging should be enabled in production builds](https://github.com/bwinton/SnoozeTabs/commit/9727ddee971e37ba8c348de8132b804af745c341) for our next release, so maybe more folks will be able to see this log chatter if/when this issue rears it's head.

**Comment by lmorchard** [comment] 2017-03-09 18:13
But, FWIW until that next release, the dev build for our current release (v1.0.14) can be picked up as a .zip file to use with about:debugging here:

https://256-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.YQThUqu/snoozetabs-dev.zip

**Comment by pdehaan** [comment] 2017-03-14 17:35
I also could not reproduce this on Friday with my 4-5 snoozes that I added. Each one of my snoozed tabs unsnoozed. ¯\\\_(ツ)\_/¯

**Comment by ckprice** [comment] 2017-03-14 17:38
I'm moving this into the Next milestone. As Les noted we'll have some logging available with the new release.

**Comment by lmorchard** [comment] 2017-03-21 21:51
Anyone else reproduced this? I've had later today and week-old tabs wake after snooze, and I can't find any reason for this to happen in the code 😟

**Comment by wresuolc** [comment] 2017-03-28 17:37
Sounds like we can't reproduce it and no one has mentioned it for a while.  There is additional logging now so if anyone runs into this please include your browser console output.  Closing for now. Thanks.

**Closed by wresuolc** 2017-03-28 17:37 UTC
