### ISSUE TITLE
UI Issue on selecting the date and time field.

### ISSUE THREAD

**Issue by Radhraj** [bwinton/SnoozeTabs#355] opened 2017-08-11 12:00 UTC
Steps to reproduce:
1.	Open the browser with snooze plugin enabled.
2.	Select any time and browse down for selecting the minutes.

Expected result:

- As and when you scroll down to select date and time, the dropdown UI must expand to get the complete list of values.

Actual result:

- The dropdown values seems to be truncated/hidden.

Attached Screenshot:
![uiissueonselectingtime](https://user-images.githubusercontent.com/30893077/29212620-2b86b6c2-7ebd-11e7-9a03-21029510b299.gif)

**Comment by SoftVision-EmilPasca** [comment] 2017-08-11 14:41
I have managed to reproduce this issue on Mac OS 10.12 and Windows 10 with Firefox release (54.0.1), the latest Firefox release (55.0.1) and the latest Nightly (57.0a1-20170810100255).

Seems that dropdown is truncated and for the hour values you have no more than four possible options to choose from, as for the minutes dropdown you can not go beyond value 56.

**Comment by Radhraj** [comment] 2017-08-11 15:01
Yes ! Regarding the values not going beyond 56, I have reported another issue.
Please have a look at #356

**Comment by rontav** [comment] 2017-12-01 12:31
@SoftVision-EmilPasca  Is anyone on this? I would like to help out.

I propose to use (at least) the time input parser from [this repo](http://jonthornton.github.io/jquery-timepicker/).

**Comment by SoftVision-EmilPasca** [comment] 2017-12-04 17:30
Hi @rontav, thanks for reaching out to us. 
In the next 2 weeks we're going to figure out what is the plan with the experiment and maybe afterwards we will contact you on this matter.

**Comment by johngruen** [comment] 2018-01-10 19:55
So maybe the react component is supposed to respect the bounds of the wrapper, but if not, we need a UI suggestion.

**Comment by sevaan** [comment] 2018-01-16 21:48
Hopefully the react component doesn't have to respect the bounds of the wrapper. But if so...

Quick temp fix while we solve the real issue: open the drop-down above the field.
Better fix: Maybe an editable textfield with the colon as the time delimeter fixed in the field, and just the am/pm can be a drop-down.

**Comment by lmorchard** [comment] 2018-01-18 20:04
Hmm, I can't reproduce this either. When I click on the time, the selectors open upward and not downward. Going to close, but feel free to reopen if anyone else can reproduce

**Closed by lmorchard** 2018-01-18 20:04 UTC

**Comment by Radhraj** [comment] 2018-01-25 05:19
@sevaan Able to reproduce this issue even so! Have tested the same for 57.0.4(Firefox) ,Windows 10.
