### ISSUE TITLE
Flashing Snooze Icon should end on Snooze Tabs icon, not site favicon

### ISSUE THREAD

**Issue by sevaan** [bwinton/SnoozeTabs#132] opened 2017-02-01 16:46 UTC
For tabs that have been returned to a user, we flash the Snooze Tabs icon over the favicon to call attention to the tab. Currently after flashing it shows the site's favicon. It should, however, show the Snooze Tabs icon until the user clicks on the tab, at which point the favicon is shown.

Correct:
<img width="268" alt="screen shot 2017-02-01 at 11 45 54 am" src="https://cloud.githubusercontent.com/assets/473531/22516505/0182ed94-e874-11e6-8599-b2fc3b208b49.png">

Incorrect:
<img width="266" alt="screen shot 2017-02-01 at 11 45 43 am" src="https://cloud.githubusercontent.com/assets/473531/22516516/05d6122c-e874-11e6-92fb-492197078524.png">

**Comment by lmorchard** [comment] 2017-02-03 18:15
Hmm, can't reproduce locally. My tabs seem to be ending on the Snooze Tabs icon. Still happening? Or did we fix this somewhere?

**Comment by sevaan** [comment] 2017-02-03 19:17
This was from your last PR regarding visual tweaks. I can't seem to replicate the original issue, although now the SnoozeTabs logo doesn't disappear when I click on the recalled tab.

**Comment by lmorchard** [comment] 2017-02-03 19:21
That styling PR didn't touch anything around the tab logo, though. So I'm wondering if something somewhere else is affecting it

**Comment by ckprice** [comment] 2017-02-07 18:37
Unable to repro, maybe was fixed in a commit.

**Closed by ckprice** 2017-02-07 18:37 UTC
