### ISSUE TITLE
Icon is not visible on any site except about:*

### ISSUE THREAD

**Issue by dikel** [bwinton/SnoozeTabs#359] opened 2017-08-17 17:26 UTC
I'm using firefox nightly on linux with dark theme. On every website which is not about:* the SnoozeTabs icon is almost invisible [link](https://imgur.com/a/BnF5r).

**Comment by SoftVision-EmilPasca** [comment] 2017-08-18 07:38
@dikel Thank you very much for reporting this issue, however, this seems like a duplicate of #67 .

**Closed by SoftVision-EmilPasca** 2017-08-18 07:38 UTC
