### ISSUE TITLE
backup/restore snoozed tabs

### ISSUE THREAD

**Issue by gherghel** [bwinton/SnoozeTabs#466] opened 2018-11-09 08:20 UTC
Show me a method to backup snoozed tabs and to restore them later.

**Comment by pdehaan** [comment] 2018-11-09 16:01
I think this is a dupe of #454

**Comment by AussieGit** [comment] 2019-07-18 01:18
Is there a workaround to restore my 80 odd tabs from an old profile to a new FF profile? Where is the data saved? I can see a Snoozed Tabs folder in my bookmarks which syncs across but it does not restore the tabs in SnoozeTab itself. Any workaround would really be apprecoated as I am too lazy to manually resnooze..

**Comment by bwinton** [comment] 2021-08-29 16:27
Closing as a dupe… Thanks for the report!

**Closed by bwinton** 2021-08-29 16:27 UTC
