### ISSUE TITLE
Unable to enable any test pilot experiments

### ISSUE THREAD

**Issue by sivaraam** [bwinton/SnoozeTabs#348] opened 2017-08-07 16:33 UTC
This seems to be an issue with *test pilot* in general but I couldn't find the right place to file this and hence creating an issue here, sorry. Let me know if there's any other place that's more appropriate for this one.

On Nightly, when I try to enable SnoozeTabs, or any other experiment for that matter, from the test pilot website it tells me to **install** test pilot and enable the experiment though I have already installed it. Note the test pilot icon in the toolbar in the following screen shot.

![screenshot from 2017-08-07 21-53-51](https://user-images.githubusercontent.com/12448084/29036068-88e7674e-7bbb-11e7-82c8-8a7c4dbc0feb.png)

When I hit the button, it says test pilot has been installed successfully and the *infinite* install progress bar never stops!

**Device details***
*User Agent* : Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
*Operating system* : Debian GNU/Linux buster/sid 64-bit

**Comment by lmorchard** [comment] 2017-08-07 20:52
Sounds like a duplicate of https://github.com/mozilla/testpilot/issues/2689

**Closed by lmorchard** 2017-08-07 20:52 UTC
