### ISSUE TITLE
Time picker opens to bottom and gets cut off

### ISSUE THREAD

**Issue by scheinercc** [bwinton/SnoozeTabs#364] opened 2017-10-11 10:41 UTC
Cut off time picker - snoozetabs 1.0.20 + Firefox 58 Build ID 20171010055346 on macOS 10.11
<img width="330" alt="screen shot 2017-10-11 at 21 36 31" src="https://user-images.githubusercontent.com/817856/31435831-a90562da-aecc-11e7-968d-5632ae1f2484.png">

working time picker  - snoozetabs 1.0.17 + Firefox 58 Build ID 20171008220130 on macOS 10.11
<img width="328" alt="screen shot 2017-10-11 at 22 18 05" src="https://user-images.githubusercontent.com/817856/31437754-181f93de-aed2-11e7-916c-10b0b6f8d1a7.png">

**Comment by rontav** [comment] 2017-12-01 12:34
Duplicate of #356

**Comment by SoftVision-EmilPasca** [comment] 2018-01-18 15:45
This issue is no longer reproducible, I have tested this on Mac 10.12, Windows 10 x64 and Ubuntu 14.04 x64 with the latest Firefox Release (57.0.4) and latest Nightly (59.0a1-20180118012136) using the latest Snoozetabs (1.0.21 - downloaded from https://circleci.com/gh/bwinton/SnoozeTabs/651#artifacts/containers/0)

**Closed by SoftVision-EmilPasca** 2018-01-18 15:45 UTC
