### ISSUE TITLE
Formatting Bugs on Panel

### ISSUE THREAD

**Issue by johngruen** [bwinton/SnoozeTabs#207] opened 2017-02-23 22:24 UTC
I've seen, and gotten reports of, the panel looking condensed and missing the pick time/date field: 

I'm running Release on MacOS with extension version 1.0.13

<img width="315" alt="screen shot 2017-02-23 at 5 00 37 pm" src="https://cloud.githubusercontent.com/assets/3323249/23281833/d4cb7cb4-f9ec-11e6-8038-683a324bd2f1.png">

**Comment by johngruen** [comment] 2017-02-23 22:27
Possibly related, seeing similarly mushed UI on the manage view with no snoozes: 
<img width="300" alt="screen shot 2017-02-23 at 5 24 18 pm" src="https://cloud.githubusercontent.com/assets/3323249/23281981/53da7a1e-f9ed-11e6-8db5-8f5801e6d695.png">

**Comment by TheClownDE** [comment] 2017-02-24 09:33
Same Problem here.
Also after clicking on "@8pm" to select date/time.

![problem](https://cloud.githubusercontent.com/assets/17886517/23298095/8841f946-fa7c-11e6-9844-1ead7ed15ec4.jpg)

**Comment by bwinton** [comment] 2017-03-02 16:22
Dupe of #179, as far as I can tell.  Thanks!

**Closed by bwinton** 2017-03-02 16:22 UTC
