### ISSUE TITLE
invalid URI: “snooze-bootstrap.js” on Waterfox

### ISSUE THREAD

**Issue by MiZiGe** [bwinton/SnoozeTabs#363] opened 2017-10-08 22:25 UTC
Hi, the snoozetab menu shows no time/date options, only "..." in the current version of 64bWaterfox.
Not sure though whether this would considered a relevant issue since it is not FireFox per se; however this was working prior to the last upgrade.

Error in console:
Snooze Tabs (bootstrap) init  snooze-bootstrap.js:1:120
Snooze Tabs (bootstrap) resize (pending) 320  snooze-bootstrap.js:1:120
Snooze Tabs (bootstrap) resize (handled) 320 toolbar  snooze-bootstrap.js:1:120
Snooze Tabs (bootstrap) load FE  snooze-bootstrap.js:1:120
‘src’ attribute of <script> element is not a valid URI: “snooze-bootstrap.js”  {20478821-77ea-430b-9525-551e22f691f5}:1

Browser:
Waterfox 55.2.0 (64-bit)

Screenshot
![image](https://user-images.githubusercontent.com/4993005/31321558-466d290a-ac88-11e7-8bd7-c7349915e230.png)

**Comment by SoftVision-EmilPasca** [comment] 2017-10-09 06:26
Hi @MiZiGe , thanks for reporting this. This looks like a dupe of #328, can you please specify the add-ons you have installed?

**Comment by MiZiGe** [comment] 2017-10-09 22:02
Hi, here is the list:

Activity Stream | 1.14.3
Adblock Plus | 2.9.1
Add-on Compatibility Reporter | 2.2.4
Classic Theme Restorer | 1.7.1
Download Status Bar | 15.0.0.1
DownThemAll! | 3.0.8
feedly | 16.0.528.1-signed.1-signed
Firefox Lightbeam | 2.0.3
Firefox Notes | 1.7.1
Greasefire | 1.0.8.1-signed.1-signed
Greasemonkey | 3.17
HTTPS Everywhere | 2017.10.4
IDM Integration Module | 6.29.1
Min Vid | 0.4.5
Nightly Tester Tools | 3.1
NoScript | 5.1.1
RefControl | 0.8.17.1-signed.1-signed
Send to Kindle for Mozilla Firefox | 1.0.2.76
snoozetabs | 1.0.20
Stylish | 2.0.7
Test Pilot | 2.0.4-dev-18ce799
TinEye Reverse Image Search | 1.3.2
Wayback Machine | 1.8.1
WOT: Web of Trust, Website Reputation   Ratings | 20171003.1wot
YouTube Center | 2.1.0.1-signed.1-signed

Please note I did not install any new addons recently.

**Comment by bwinton** [comment] 2021-08-28 21:46
I'm afraid we don't support Waterfox… Hopefully this has started working for you since the bug was reported, but if not, I think your best bet is to contact the Waterfox devs. Best of luck!

**Closed by bwinton** 2021-08-28 21:46 UTC
