### ISSUE TITLE
Cannot select the time for snooze more than 20 hours and 56 minutes

### ISSUE THREAD

**Issue by Radhraj** [bwinton/SnoozeTabs#356] opened 2017-08-11 12:40 UTC
Steps to reproduce:
1.	Open the browser with snooze plugin enabled.
2.	Try to select the HH:MM more than 20:56 .
Expected result:

- Should be able to select upto 23:59 from 00:00

Actual result:

- The drop down does not go beyond 20:56

Attached screenshot:

![canselecttimeupto56](https://user-images.githubusercontent.com/30893077/29213339-738ebc1e-7ec0-11e7-8da7-2c5f2dfbf56f.gif)

**Comment by AussieGit** [comment] 2017-11-07 23:42
I am getting this problem also. FF Quantum 57.0b13 (64bit) Windows 7

**Comment by johngruen** [comment] 2018-01-10 19:56
I think this is a dupe of the bug about the picker getting clipped, closing and we can revisit if that turns out not to be true

**Closed by johngruen** 2018-01-10 19:56 UTC
