### ISSUE TITLE
Snooze tabs must adopt the color of the panel

### ISSUE THREAD

**Issue by sivaraam** [bwinton/SnoozeTabs#210] opened 2017-02-24 12:27 UTC
I use Firefox Nightly on a Debian system. I noticed that the icon colour of SnoozeTabs is not adopting to the colour of the panel it which it is shown. All other icons such as Bookmark icon, Download icon are whit in colour while the SnoozeTabs icon remains black and as a result it seems odd and is not easy to see the icon. It would be nice if the icon adjusts it's colour according to the environment. 

**Screenshot**
![screenshot from 2017-02-24 07-04-11](https://cloud.githubusercontent.com/assets/12448084/23303446/3ab41f90-faba-11e6-88ea-55b63965c5d1.png)

**System Details**
_Browser_ : Firefox Nightly
_Operating System_ : Debian GNU/Linux 9
_Graphics_ : Wayland

**Comment by SoftVision-EmilPasca** [comment] 2017-02-24 12:42
Thank you for reporting this @sivaraam, However, I think this is a duplicate of #67.

**Closed by SoftVision-EmilPasca** 2017-02-24 12:42 UTC
