### ISSUE TITLE
Customize snooze times

### ISSUE THREAD

**Issue by Akronix** [bwinton/SnoozeTabs#332] opened 2017-06-29 18:25 UTC
Hi!

I'd like to customize the snooze times.
With this I mean to be able to define the default time for days (I prefer 10am rather than 9am) as well as for later today (11pm is too late!!)

This issue could be contained by #270, but this is simpler and smaller (I'm requesting only to set default times for the default options, not to set a custom date and time options).

**Comment by SoftVision-PaulOiegas** [comment] 2017-06-30 20:13
Hi @Akronix and thanks for the report. What you propose is interesting, we'll see what the developers think about this. 
However, there is an option for custom date and time already (Pick a date/time). Also, the "Later today" option is set to be in 3 hours from the current time of the day.

**Comment by Akronix** [comment] 2017-07-03 09:56
yeah...as for the "Later today" option I would expect to be at some time previously set by me, like _afternoon time_ (let's say around 4pm) if it's morning or _night time_ (say, around 8pm) if afternoon has already passed; rather than 3 hours later than the current random time.

If you have ever used inbox from Google, they have this feature.

**Comment by lmorchard** [comment] 2017-08-09 16:25
Going to all this a duplicate of #270 - editing existing time options is not all that different from adding new ones. (i.e. would probably require most of the same work to implement)

**Closed by lmorchard** 2017-08-09 16:25 UTC
