### ISSUE TITLE
icon is not dark theme friendly

### ISSUE THREAD

**Issue by escapewindow** [bwinton/SnoozeTabs#331] opened 2017-06-27 19:00 UTC
Similar to the Page Shot toolbar icon: Snooze Tabs' icon blends in with the dark theme.

**Comment by lmorchard** [comment] 2017-06-27 19:42
Dupe of #67 - unfortunately, we can't detect themes from webextensions to switch icons :(

**Closed by lmorchard** 2017-06-27 19:42 UTC
