### ISSUE TITLE
Snoozed tab opens twice

### ISSUE THREAD

**Issue by sivaraam** [bwinton/SnoozeTabs#480] opened 2021-02-13 16:58 UTC
For some strange reason, each time a snoozed tab is opened it opens twice instead of just once. This happens on one of my device on Firefox stable (v85.0) on Windows 10. I'm not sure of the exact reason for this and this doesn't happen on all the devices.

Any help on identifying why this is happening would be great. Let me know if more information is needed.

**Comment by JordyScript** [comment] 2021-02-27 17:17
Does this happen every time? Or has it happened occasionally ? I have had it before, but not consistently.

**Comment by sivaraam** [comment] 2021-03-01 19:03
It appears to happen consistently for me on one device. In some of my other devices it doesn't happen and everything's normal.

**Comment by neetorama** [comment] 2021-04-08 13:58
I'm experiencing the same. Snoozed tabs are restored twice - 2 tabs open, both with the same url.

**Comment by bwinton** [comment] 2021-08-29 16:42
I don't know why this is happening (maybe multiple devices are connected to your Firefox account?), but I'm going to close it as a dupe of #455, so if there's any more information, please post it there… Thanks!

**Closed by bwinton** 2021-08-29 16:42 UTC
