### ISSUE TITLE
Panel snooze options have the month wrongly displayed in the timestamp with numbers instead of letters on [cs] and [sk] localization

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#313] opened 2017-04-20 15:43 UTC
[Affected versions]:
- Release 53.0 and up
- Snooze Tabs 1.0.17

[Affected Platforms]:
- All Windows
- All MAC OS X
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://557-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.qwCtnIN/snoozetabs-1.0.17.zip) loaded as a temporary add-on.
- Have the Czech [cs] and the Slovak [sk] Firefox locale builds installed.

[Steps to reproduce]:
1. Open one of the localised Firefox builds with the profile from prerequisites and navigate to a website.
2. Click on the "SnoozedTabs" button in the browser toolbar.
3. Observe the timestamps for the suggested snooze options.

[Expected result]:
- Both months and days are abbreviated, starting with capital letters in all the timestamps.

[Actual result]:
- Months are wrongly represented by numbers in all the timestamps.

[Notes]:
- Please see below the screenshot of the issue:

![cs](https://cloud.githubusercontent.com/assets/26000308/25239565/04f09ac2-25f9-11e7-8032-cddd5b8c193f.jpg)

**Comment by lmorchard** [comment] 2017-04-20 18:59
Tracking this down and tl;dr: I think this is either working as intended or is an upstream API issue.

We use [the `Intl.DateTimeFormat` API](﻿﻿https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) to compose these date strings. For example, the [next month](https://github.com/bwinton/SnoozeTabs/blob/v1.0.17/src/lib/times.js#L50) option uses [our `long_date_time` format](https://github.com/bwinton/SnoozeTabs/blob/v1.0.17/src/lib/time-formats.js#L12) which is built like so:
```javascript
const uiLocales = [browser.i18n.getUILanguage().replace('_', '-'), 'en-US'];
const format = new Intl.DateTimeFormat(uiLocales, { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' })
```
Maybe @flodolo or @zbraniecki can see if there's something incorrect we're doing here?

**Comment by flodolo** [comment] 2017-04-21 06:32
Let's see if zibi has a better answer, from CLDR I would expect cs to have an abbreviated month
http://www.unicode.org/cldr/charts/31/summary/cs.html#1916

**Comment by zbraniecki** [comment] 2017-04-21 06:48
Yup, it's as intended.
For 'cs' and 'sk', the short patterns use numeric values:

http://www.unicode.org/cldr/charts/31/summary/cs.html#2207
http://www.unicode.org/cldr/charts/31/summary/cs.html#2188

I don't know why but the result is that all browsers return this:
```javascript
 (new Intl.DateTimeFormat('cs', { weekday: 'short', month: 'short', day: 'numeric' })).format(0)
"st 31. 12."
```

You can test in Chrome,  Safari, Firefox... also, that's the format Firefox UI will return as well.

If we believe it to be wrong, it would be best to fix it at the source and benefit all projects internationalizations. You can report it at http://unicode.org/cldr/trac

**Comment by lmorchard** [comment] 2017-04-21 15:53
> Yup, it's as intended.

For Snooze Tab purposes then, I'll say this works as intended and close this issue.

**Closed by lmorchard** 2017-04-21 15:53 UTC
