### ISSUE TITLE
Snoozed tabs didn't open

### ISSUE THREAD

**Issue by scheinercc** [bwinton/SnoozeTabs#322] opened 2017-04-28 10:46 UTC
I had two tabs snoozed until today, one for 5pm, one for 6pm. Around 6:30pm I realised that they haven't opened yet. I opened one via "Manage snoozed tabs", navigated to a new page and only when I saved this tab for a later date the other two opened simultaneously. First time that happened. 
System: 55.0a1 (2017-04-27) (64-bit) on macOS

**Comment by lmorchard** [comment] 2017-04-28 15:50
Hmm, we've had a similar report before (#234) but have not been able to reliably reproduce the issue to find the cause. I'll leave this open to see if anyone else sees it again. You don't happen to have any browser console error messages, do you? (Probably not, since I'd be surprised if you had it open at the time in normal use)

As for the sudden opening of the late snoozed tabs - we've got code that opens up everything that's due or overdue. That happens when a) a timer goes off or b) anything changes the set of snoozed tabs (e.g. when snoozing, updating, or deleting). 

Sounds like at some point you lost the timer that should have gone off for 5pm & 6pm, but I don't know why that would have happened.

**Comment by albinhh** [comment] 2017-04-29 06:45
I had similar strange behaviour as well. I didn't make much of it, because I thought it was due to "user error" but I will try to reproduce it next time it happens and post my findings.

**Comment by scheinercc** [comment] 2017-04-29 14:48
Will keep an eye out and report it here if it happens again, too.

**Comment by jibe-b** [comment] 2017-05-05 14:46
I have the same behaviour since 2 or 3 days.

**Comment by lmorchard** [comment] 2017-05-05 15:52
> I have the same behaviour since 2 or 3 days.

Did you happen to see any error messages in the log?

**Comment by jibe-b** [comment] 2017-05-05 23:38
May I ask which log I should check?

**Comment by lmorchard** [comment] 2017-05-08 16:02
> May I ask which log I should check?

The browser console - under the Tools > Web Developer > Browser Console menu

**Comment by latk** [comment] 2017-09-30 09:41
I may have managed to reproduce this or a related issue:

 1. Snooze a tab for n minutes (n >= 2) by manually selecting a time.
 2. Suspend the browser, e.g. by hibernating the host OS. Issuing a SIGSTOP to Firefox should also work.
 3. Wait for > n minutes. The timer should have fired during this time, but obviously can't since the process is not running.
 4. Resume Firefox. Expectation: The snoozed tab appears within a few seconds.
 5. Wait for n minutes.
 6. The snoozed tab appears.

I checked this with n = 2 minutes, under FF 55.0.2, using Ubuntu 16.04 as host OS.

The observed behaviour indicates the timer does not fire at the next available time after the due time point, but after the duration (due time - now) has elapsed.

This may very well be an upstream problem in FF's handling of `browser.alarms`, e.g. if the pending alarms are not updated to account for sudden jumps in time. But that's conjecture.

This seems to be very similar to #295 except that this issue can manifest without having to quit the browser.

This could be solved by checking for due tabs every minute, but polling seems inelegant.

**Comment by johngruen** [comment] 2018-01-10 19:38
@SoftVision-CarmenFat were you ever able to reproduce this issue? We are trying to put together a new release here, and it would be good to have some documented cases.

**Comment by SoftVision-CarmenFat** [comment] 2018-01-11 15:05
@johngruen

Neither I and @Softvision-EmilPasca were able to reproduce the issue since it was reported. All the snoozed tabs were brought back without any trouble.

**Comment by lmorchard** [comment] 2018-01-18 19:58
Going to close this for now... I can't reproduce and we don't really have anything that seems obvious to fix. Added a fallback timer that fires every minute to open late tabs, just in case

**Closed by lmorchard** 2018-01-18 19:58 UTC
Labels: bug

**Comment by hoelzro** [comment] 2018-02-16 23:39
This appears to be resolved in master, but I've seen this with my current version of the plugin (1.0.20) - I'm guessing that since I'm on Linux and it only happens when I suspend, it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1359403.  I'm guessing the fallback timer will fix this once that's released - just adding more information!
