### ISSUE TITLE
Unable to unsnooze non-HTTP[S] urls

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#70] opened 2017-01-06 23:32 UTC
### Steps to reproduce:

1. Navigate to "data:image/gif;base64,R0lGOD lhCwAOAMQfAP////7+/vj4+Hh4eHd3d/v7+/Dw8HV1dfLy8ubm5vX19e3t7fr 6+nl5edra2nZ2dnx8fMHBwYODg/b29np6eujo6JGRkeHh4eTk5LCwsN3d3dfX 13Jycp2dnevr6////yH5BAEAAB8ALAAAAAALAA4AAAVq4NFw1DNAX/o9imAsB tKpxKRd1+YEWUoIiUoiEWEAApIDMLGoRCyWiKThenkwDgeGMiggDLEXQkDoTh CKNLpQDgjeAsY7MHgECgx8YR8oHwNHfwADBACGh4EDA4iGAYAEBAcQIg0Dk gcEIQA7"
1. Snooze the tab.
1. Try and restore the snoozed tab via "Manage Snoozed Tabs".

### Actual results:
Clicking on the data URI result doesn't launch a new tab.

![are_we_rebels_yet__and_data_url_-_yahoo_search_results_and_really_long_domain_name_-_yahoo_search_results](https://cloud.githubusercontent.com/assets/557895/21736381/29723246-d425-11e6-80e1-1e0924f30eb2.png)

**Comment by pdehaan** [comment] 2017-01-07 00:57
Also happens to file:/// URLs, if you accidentally snooze a downloaded SVG from the open PR:
file:///Users/pdehaan/Downloads/NextOpen.svg

![firefox_developer_edition_and_package_json_ _snoozetabs](https://cloud.githubusercontent.com/assets/557895/21737762/1fa9786c-d431-11e6-9c3b-ccfbb646fe78.png)

**Comment by lmorchard** [comment] 2017-01-10 16:50
I think this is a dupe of #59

**Closed by lmorchard** 2017-01-10 16:50 UTC
