### ISSUE TITLE
The background of the "Snooze!" button is wrongly colored in light grey when hovering it

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/SnoozeTabs#441] opened 2018-02-28 08:15 UTC
[Affected versions]:
- Release 58.0.2 and up
- Snooze Tabs 1.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://github.com/bwinton/SnoozeTabs/releases/tag/1.1.0) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Navigate to a website (e.g. www.wikipedia.org) and click on the "SnoozedTabs" button.
3. Click the suggested time for one of the options in the panel (e.g. "@1pm").
4. Hover the "Snooze!" button and observe what happens next.

[Expected result]:
- The background of the "Snooze!" button is colored in a dark blue.

[Actual result]:
- The background of the "Snooze!" button is colored in a light grey.

[Notes]:
- Attached a screen recording of the issue:

![hover button](https://user-images.githubusercontent.com/26000308/36776903-1de089e8-1c70-11e8-97f6-f1900e68abbf.gif)

**Comment by bwinton** [comment] 2021-08-29 16:54
Dupe of #440, I think.

**Closed by bwinton** 2021-08-29 16:54 UTC
Labels: [QA]:Minor issue
