### ISSUE TITLE
[l10n] SnoozedTabs context-menu option is missing

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [bwinton/SnoozeTabs#178] opened 2017-02-14 18:02 UTC
[Affected versions]:
- Firefox 51.0.1
- Snooze Tabs 1.0.12  (l10n branch, built on 02/14/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.12 -l10n branch, built on 02/14/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Right-click on the tab and observe the context-menu options.

[Expected result]:
- SnoozedTabs context-menu option is displayed.

[Actual result]:
- SnoozedTabs context-menu option is missing.

[Notes]:
- Attached a screen recording of the issue:
![snoozetabs_contextmenu-missing](https://cloud.githubusercontent.com/assets/20083658/22942027/71e34828-f2f0-11e6-9112-93cec8ce9199.gif)

**Comment by flodolo** [comment] 2017-02-14 18:13
It seems to work for Italian with "npm start" locally. I wonder if part of the problem is the lack of localization

![schermata 2017-02-14 alle 19 12 17](https://cloud.githubusercontent.com/assets/3644868/22942401/b69b037c-f2e9-11e6-8865-6554df7c76a2.png)

**Comment by lmorchard** [comment] 2017-02-14 18:35
FWIW, I think this is only available on Firefox Nightly? Not sure exactly which version this context menu API was added

**Comment by bwinton** [comment] 2017-02-14 18:44
It looks like [it landed in 53](https://bugzilla.mozilla.org/show_bug.cgi?id=1316020#c24).

**Comment by bwinton** [comment] 2017-02-14 18:50
(Closing based on that. 😉)

**Closed by bwinton** 2017-02-14 18:50 UTC
