### ISSUE TITLE
user-defined custom buttons in popup menu 

### ISSUE THREAD

**Issue by smartfonreddit** [bwinton/SnoozeTabs#344] opened 2017-07-26 19:24 UTC
It's been suggested by others to allow the user to modify the default scheduling times for the existing buttons. This one is a feature request to allow the user to add a button in the popup menu with a user-defined name and time.

The custom calendar picker requires many steps. It isn't as easy as having the user set a custom value that he knows he's going to use a lot.
For me the "Later Today" means at 6:00PM. I'd also add a new entry named "Evening" at 10:00PM. Custom entry for 1 hour would be useful too. Users have different use patterns. Some people's evening is during a day time, so having the ability to set custom values could help them as well.

Thanks for the excellent project!

**Comment by lmorchard** [comment] 2017-08-09 16:22
Duplicate of #270

**Closed by lmorchard** 2017-08-09 16:22 UTC
