### ISSUE TITLE
Customizable time drop down and 'pick a date/Time' option are displayed intermittently

### ISSUE THREAD

**Issue by prashant363** [bwinton/SnoozeTabs#222] opened 2017-02-27 18:07 UTC
Snoozing a tab for say @3am is impossible as clock to set time is displayed intermittently.
The same is the case with 'pick a Date/Time' 

Is this expected? or a certain step needs to performed for it?

Environment: Win 7, 64 bit , FF 51
[Manage_snooze_customTime.zip](https://github.com/bwinton/SnoozeTabs/files/804543/Manage_snooze_customTime.zip)

**Comment by SoftVision-EmilPasca** [comment] 2017-02-28 09:31
Thank you for reporting this @prashant363. However, I think this is a duplicate of #179.

**Closed by SoftVision-EmilPasca** 2017-02-28 09:31 UTC

**Comment by prashant363** [comment] 2017-02-28 11:17
Thankyou @SoftVision-EmilPasca  :)
