### ISSUE TITLE
"Pick a Date/Time" option not always visible

### ISSUE THREAD

**Issue by mmmavis** [bwinton/SnoozeTabs#236] opened 2017-03-03 23:21 UTC
First of all... thanks for making this awesome addon! 👍 👏 🎉 #notmoretabhell 😂 

I started using it today and discovered a bug on Firefox v51.0.1 on Max OS X 10.11.6. It seems like the option menu doesn't always get fully expanded every time.

![snooze-tabs-context-menu](https://cloud.githubusercontent.com/assets/2896608/23572456/11239128-0024-11e7-9bc7-26a12fdb5329.gif)

This can be reproduced on another webpages as well.

**Comment by SoftVision-EmilPasca** [comment] 2017-03-06 08:58
Thank you for reporting this @mmmavis. However, this is a duplicate of #179.

**Closed by SoftVision-EmilPasca** 2017-03-06 08:58 UTC
